export const Questions = [
    {
      prompt: "What is the sum of 48 and 73?",
      optionA: "115",
      optionB: "121",
      optionC: "126",
      optionD: "131",
      asnwer: "optionB",
    },
    {
      prompt: "If you subtract 56 from 89, what is the result?",
      optionA: "45",
      optionB: "34",
      optionC: "33",
      optionD: "23",
      asnwer: "optionC",
    },
    {
      prompt: "What is the product of 9 and 7?",
      optionA: "56",
      optionB: "63",
      optionC: "72",
      optionD: "65",
      asnwer: "optionB",
    },
    {
        prompt: "If you divide 84 by 12, what is the quotient?",
        optionA: "7",
        optionB: "6",
        optionC: "8",
        optionD: "9",
        asnwer: "optionA",
      },
      {
        prompt: "Which property of arithmetic states that the order of numbers doesn't matter in addition?",
        optionA: "Commutative Property of Addition",
        optionB: "Associative Property of Addition",
        optionC: "Distributive Property",
        optionD: "Identity Property of Addition",
        asnwer: "optionA",
      },
      {
        prompt: "What is the additive inverse of -36?",
        optionA: "-72",
        optionB: "36",
        optionC: "-18",
        optionD: "-36",
        asnwer: "optionB",
      },
      {
        prompt: " If you round 98 to the nearest ten, what is the result?",
        optionA: "90",
        optionB: "105",
        optionC: "95",
        optionD: "100",
        asnwer: "optionD",
      },
      {
        prompt: "What is the area of a square with a side length of 9 meters?",
        optionA: "18 square meters",
        optionB: "72 square meters",
        optionC: "81 square meters",
        optionD: "9 square meters",
        asnwer: "optionC",
      },
      {
        prompt: "Which of the following numbers is prime?",
        optionA: "12",
        optionB: "39",
        optionC: "28",
        optionD: "17",
        asnwer: "optionD",
      },
      {
        prompt: " If a car travels at a speed of 55 miles per hour for 3 hours, how far does it travel?",
        optionA: "165 miles",
        optionB: "150 miles",
        optionC: "160 miles",
        optionD: "175 miles",
        asnwer: "optionA",
      },
  ];